Constellation-Labs/tessellation

project/Dependencies.scala
`slf4j-api` needs to be excluded since `hikari` a transitive dependency of `doobie` depends on `slf4j-api` in version `2.0` which is incomaptible with `1.7` that we currently use everywhere.
=> Fix logging

modules/core/src/main/scala/org/tesselation/domain/trust/storage/TrustStorage.scala, modules/core/src/main/scala/org/tesselation/http/routes/ClusterRoutes.scala, modules/core/src/main/scala/org/tesselation/http/routes/TrustRoutes.scala, modules/core/src/main/scala/org/tesselation/infrastructure/trust/storage/TrustStorage.scala, modules/core/src/main/scala/org/tesselation/modules/HttpApi.scala, modules/core/src/test/scala/org/tesselation/http/routes/TrustRoutesSuite.scala, modules/core/src/test/scala/org/tesselation/infrastructure/trust/storage/TrustStorageSuite.scala, modules/shared/src/main/scala/org/tesselation/schema/cluster.scala, modules/shared/src/main/scala/org/tesselation/schema/trust.scala
Moved trust related schema to own object. Add calculation for offset of trust and defined case class / Kryo registrar update. Corresponding test of http routes.
=> Add p2p routes for trust polling from storage & test. 

modules/core/src/main/scala/org/tesselation/Main.scala, modules/core/src/main/scala/org/tesselation/domain/cluster/programs/TrustPush.scala, modules/core/src/main/scala/org/tesselation/http/routes/ClusterRoutes.scala, modules/core/src/main/scala/org/tesselation/infrastructure/gossip/RumorHandlers.scala, modules/core/src/main/scala/org/tesselation/infrastructure/trust/handler.scala, modules/core/src/main/scala/org/tesselation/modules/HttpApi.scala, modules/core/src/main/scala/org/tesselation/modules/Programs.scala, modules/shared/src/main/scala/org/tesselation/schema/kryo/package.scala, modules/shared/src/main/scala/org/tesselation/schema/trust.scala
Simple program takes internal updates and publishes latest PublicTrust
snapshot. Avoided incremental updates to keep it simpler as data is
extremely small (labels and observations only.)
Triggered from CLI trust update after storage is updated. Spreads
gossip and add an empty handler which will be used in subsequent PR.
Adds randomization factor to handle issues with reversions in scores
to avoid problem with seenHashes. Removed @newtype due to addition
of UUID for randomness.
=> Add TrustPush program connecting trust update with gossip

modules/core/src/main/scala/org/tesselation/config/Config.scala, modules/core/src/main/scala/org/tesselation/config/types.scala, modules/core/src/main/scala/org/tesselation/domain/trust/storage/TrustStorage.scala, modules/core/src/main/scala/org/tesselation/http/p2p/P2PClient.scala, modules/core/src/main/scala/org/tesselation/http/p2p/clients/TrustClient.scala, modules/core/src/main/scala/org/tesselation/infrastructure/trust/TrustDaemon.scala, modules/core/src/main/scala/org/tesselation/infrastructure/trust/storage/TrustStorage.scala, modules/core/src/main/scala/org/tesselation/modules/Daemons.scala
Model code not yet enabled, so mostly a stub for now.
Add a configuration for trust with an interval for daemon. Daemon is structured
same as Gossip daemon in terms of classes used. Relies on trustStorage data assumed to be updated by gossip and updates internal storage with predictions.
This is for feature parity with existing codebase. Long term requirements will need model updates.
=> Trust implemented as Daemon using gossip.

modules/core/src/main/scala/org/tesselation/infrastructure/trust/SelfAvoidingWalk.scala, modules/core/src/test/scala/org/tesselation/trust/TrustCalculationSuite.scala
Very basic and simple data, model already has stack error fixed so enabling it should be fine. Data generator will be
ported over separately, this is the minimal verification
that model is producing scores and not overriding labels.
=> Enable model with simple transitive test.

modules/core/src/test/scala/org/tessellation/trust/DataGenerator.scala, modules/core/src/test/scala/org/tessellation/trust/SybilAttackSuite.scala
This is a very 'weak' test in the sense that new variations of it should be proposed, but it demonstrates an example of where SAW beats conventional EigenTrust for 2 equivalent networks with a relative local scoring function.
This isn't deterministic but it's most likely always going to yield some defensive factor above 5, may need to reduce assertion depending but subject to change.
I typically see defensive factor of around ~5-10 in random tests. Plan to add example with EigenTrust but EigenTrust here should almost always yield ~ defense factor of 1 since the networks are otherwise randomly initialized with only a single edge.
=> Implement basic sybil attack test on weak edge

build.sbt, modules/core/src/main/scala/org/tessellation/infrastructure/trust/DATT.scala, modules/core/src/main/scala/org/tessellation/infrastructure/trust/EigenTrust.scala, modules/core/src/main/scala/org/tessellation/infrastructure/trust/SelfAvoidingWalk.scala, modules/core/src/main/scala/org/tessellation/infrastructure/trust/TrustDaemon.scala, modules/core/src/main/scala/org/tessellation/infrastructure/trust/TrustModel.scala, modules/core/src/test/scala/org/tessellation/trust/DataGenerator.scala, modules/core/src/test/scala/org/tessellation/trust/SybilAttackSuite.scala, modules/core/src/test/scala/org/tessellation/trust/TrustCalculationSuite.scala
This demonstrates sybil attack weakness of EigenTrust and
benefits of the two other models. DATT code covers weighted
and non weighted test examples.
EigenTrust code has a build conflict with this and we can't
easily port over the alpha testbed version. Adapted it quickly
to scala ignoring experiences / opinions (which we need to
do anyways.) Mainly used for comparison purposes here
in demonstration of defense factor for this test.
Implemented an average model between these three to cover
future proximity test which SAW / DATT are currently
weak against, will be demonstrated in separate PR.
Note, in developing this and debugging, I found the data generator code was broken from before and was not generating proper edges. The invocation of random was yielding the same distance value for all …
=> Implement compound model - EigenTrust / DATT / SAW & Tests

modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockStorage.scala
Currently going through NonEmptyMap resulted in unwanted deduplication because of the way Order is defined for BlockReference - to be revised and possibly fixed in another PR.
=> Fix checking parent acceptance in DAG L1

modules/dag-shared/src/main/scala/org/tessellation/dag/block/BlockValidator.scala, modules/dag-shared/src/main/scala/org/tessellation/dag/block/config/BlockValidatorConfig.scala
Needed to fix an issue with block validation during DAG L1 block consensus.
=> Extract block validator config and allow overriding signers count

modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
Lack of error handling caused the DAG block creation stream to fail.
=> Handle block storing error in DAG L1

modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/P2PClient.scala, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Programs.scala, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Storages.scala, modules/sdk/src/main/scala/org/tessellation/sdk/cli/L0PeerOpts.scala, modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/programs/L0PeerDiscovery.scala, modules/sdk/src/main/scala/org/tessellation/sdk/domain/cluster/storage/L0ClusterStorage.scala, modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/L0ClusterClient.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/cluster/storage/L0ClusterStorage.scala, modules/shared/src/main/scala/org/tessellation/ext/cats/data/package.scala, modules/shared/src/main/scala/org/tessellation/schema/peer.scala
I will still look into whether L0 nodes can be discovered from L1 peers (except for the initial node starting L1 layer). But this is a working and tested implementation of L0 peers discovery based on declaring initial L0 peer during node startup. Doing it that way also seems correct to me.
=> L0 peers discovery functionality

SETUP.md
Generalized overall setup instructions and made them OS agnostic. Added OS dependent instructions for installing JDK 8, SBT, Docker, and Kubernetes. This is a documentation change.
=> Generalized the setup instructions to be OS agnostic

modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala, modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusFunctions.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/declaration.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/trigger.scala
Currently, trigger type is not used and it's hardcoded to be always `TimeTrigger`. In the next submissions, I will add usages for both `EventTrigger` and `TimeTrigger`.
=> Majority on trigger type

modules/shared/src/main/scala/org/tessellation/security/Hex.scala
Before this change, there was a possibility that calling `.shortValue` would throw an error.
=> Fix short format for Hex class

modules/core/src/main/scala/org/tessellation/http/routes/GlobalSnapshotRoutes.scala, modules/shared/src/main/scala/org/tessellation/ext/http4s/headers/negotiation.scala
By default, the endpoint continues to return binary data, however when requesting `Accept: application/json` a JSON is returned.
=> Glogal snapshot json endpoint

modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStorage.scala
FYI: this also impacts the way the healthcheck will work from now on for the corner case of checking proposal for an obsolete snapshot consensus. Example: if some slower node starts consensus for snapshot 10 when our node has already finished consensus for snapshot 11 we will respond with not required even if we had a proposal at height 10 originally - we will have those proposals cleaned up already. After analyzing it it doesn't seem like something we should be concerned about in the algorithm logic.
=> Fix memory leak in L0 consensus storage

modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/GossipRoutes.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorStorage.scala
The core issue is a double pull from the stream. This is a fix but optimization for using strict collections instead of iterators will come next.
=> Fix rumor storage initialization

modules/core/src/main/scala/org/tessellation/config/types.scala
New distribution reflects ~4.5M in rewards per 30 days of snapshots
=> Adjust DTM weights

modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala
Previously if generated `SortedSet` was empty an arbitrary generator would discard generated instance.
=> Fix discarding arbitrary instances for Signed

modules/core/src/main/scala/org/tessellation/infrastructure/trust/handler.scala
Trust ratings transmitted via gossip are now persisted instead of ignored.
=> Update trust info via gossip.

modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala, modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala
Changed the Rosetta endpoints to use the `JSONBinarySerializer`. This is a re-implementation of PR https://github.com/Constellation-Labs/tessellation/pull/589 that is forked off of the `feature/incremental-snapshots` branch. This PR supersedes PR https://github.com/Constellation-Labs/tessellation/pull/589.
=> Change Rosetta to use JSON serializer/deserializer

modules/core/src/main/scala/org/tessellation/Main.scala, modules/core/src/main/scala/org/tessellation/http/p2p/P2PClient.scala, modules/core/src/main/scala/org/tessellation/modules/Programs.scala, modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala, modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusManager.scala, modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/PeerSelect.scala, modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/SdkP2PClient.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/MajorityPeerSelect.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/programs/Download.scala
When choosing which peer to observe, select a peer on the majority fork. This PR implements the code needed to select a peer on the majority fork for observation. It supersedes PR https://github.com/Constellation-Labs/tessellation/pull/616 and is related to PR https://github.com/Constellation-Labs/tessellation/pull/629.
=> Observe majority fork

modules/core/src/main/scala/org/tessellation/Main.scala, modules/core/src/main/scala/org/tessellation/http/p2p/P2PClient.scala, modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/SdkP2PClient.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/MajorityPeerSelect.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/programs/Download.scala
The current `PeerSelect` doesn't gracefully handles errors that are the result of it querying a `Peer` for the snapshot for a `SnapshotOrdinal` value that doesn't exist. This fixes that. It also parallelizes the queries to other `Peer`s and addresses comments that were not addressed prior to merging PR https://github.com/Constellation-Labs/tessellation/pull/630.
=> PeerSelect gracefully handles no snapshot errors

modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
Already merged to 2.0.0-alpha.6, missing on develop
=> Process currency snapshots in correct order on GL0

modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/L0GlobalSnapshotClient.scala
Changed the method of `L0GlobalSnapshotClient`'s `GetHash` to `GET` from `POST`.
=> Changed the client call to GET

modules/core/src/main/scala/org/tessellation/domain/snapshot/programs/Download.scala, modules/core/src/main/scala/org/tessellation/domain/snapshot/storages/SnapshotDownloadStorage.scala, modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/SnapshotDownloadStorage.scala
This fixes removing the forked snapshots when the node joining has the highest ordinal lower than the network it joins to. A fix for purging snapshots above the highest in the network a node joins to is still to be implemented.
=> Fix purging snapshots from persisted storage

modules/core/src/main/scala/org/tessellation/config/types.scala, modules/core/src/main/scala/org/tessellation/domain/dag/DagService.scala, modules/core/src/main/scala/org/tessellation/infrastructure/dag/DAGService.scala, modules/core/src/main/scala/org/tessellation/infrastructure/rewards/Rewards.scala, modules/core/src/test/scala/org/tessellation/infrastructure/rewards/RewardsSuite.scala, modules/core/src/test/scala/org/tessellation/trust/SybilAttackSuite.scala, modules/sdk/src/main/scala/org/tessellation/sdk/domain/transaction/TransactionValidator.scala
UPDATE 2: The only effective change for this PR will be to introduce a new rewards distribution. The majority of the other changes described below will be in a follow-up release.
We're also adding the _Stardust Primary_ address to the set of locked addresses.
UPDATE: As per Ryle's comment we recalculated the expected Epoch to be `1352274` rather than using the computation below.
Calculation for the added `EpochProgress` is based on the recently added epoch progress value of `1349352` estimated to happen on July 1st, 10am UTC. Using the _1 snapshopt / minute_ guideline,
```
scala> val July1st = Instant.parse("2023-07-01T10:00:00Z")
val July1st: java.time.Instant = 2023-07-01T10:00:00Z
scala> val July10th = Instant.parse("2023-07-10T10:00:00Z")
val July10th: java.time.Instant = …
```
=> Adjust ProgramsDistributionConfig for future epoch

modules/core/src/main/scala/org/tessellation/config/types.scala, modules/core/src/main/scala/org/tessellation/http/routes/DagRoutes.scala, modules/sdk/src/main/scala/org/tessellation/sdk/domain/transaction/TransactionValidator.scala
Transfer old stardust primary balance to new address
Add old stardust primary to locked addresses set
Exclude locked addresses from `total-supply` endpoint
Note that the balance shown in [DAG Explorer for `DAGSTARDUSTCOLLECTIVEHZOIPHXZUBFGNXWJETZVSPAPAHMLXS`](https://mainnet.dagexplorer.io/address/DAGSTARDUSTCOLLECTIVEHZOIPHXZUBFGNXWJETZVSPAPAHMLXS)
is `43,430,294.88479231 DAG`. The balance transferred in this PR is the value taken from the global snapshot `4343029488479231`, which is the same value with the decimal point moved eight places to the right.
=> One-time reward transfer to new Stardust Primary

modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/StateChannel.scala
@marcinwadon @IPadawans if fixes custom endpoints because previously Currency L1 was not syncing with Global L0 if Data was enabled
=> Enable global snapshot processing if Data is enabled

modules/core/src/main/scala/org/tessellation/infrastructure/trust/handler.scala
Isolated the trust rumor handlers logging to a separate log.
=> Isolated the trust rumor handlers logging

build.sbt, modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala, modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala, modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala, modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala, modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/StateChannelSnapshotService.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/snapshot/programs/CurrencySnapshotProcessor.scala, modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala, modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala, modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala, modules/shared/src/main/scala/org/tessellation/json/JsonBrotliBinarySerializer.scala, modules/shared/src/test/scala/org/tessellation/json/JsonBinarySerializerSuite.scala, modules/shared/src/test/scala/org/tessellation/json/JsonBrotliBinarySerializerSuite.scala, project/Dependencies.scala
A PR introducing the compression for metagraph snapshot binary. Here the implementation with Brotli algorithm. There is a second PR built on top of this one changing the compression algorithm to Gzip.
The reason there is a second one is that there is one caveat with Brotli in java.
The library used in this PR namely brotli4j (https://github.com/hyperxpro/Brotli4j) is the only one I found providing encoding/compressing functionality with Brotli. The way it works though is by using native brotli implementation provided by the host platform and by using JNI (Java Native Interface). The implementation works on macOS for sure and is tested by the library owner on other platforms like Ubuntu 18.04 or Windows Server 2022. We could run some cross platform test with GitHub Actions to check the …
=> Add json with brotli compression serializer

modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala, modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala, modules/core/src/main/scala/org/tessellation/modules/Services.scala, modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
Small cleanup of a testing flag that was used during the migration to 2.0
- Removed hardcoded testnet definition that is no longer needed in test
- Cleaned up env param that was no longer used
- ensured unit tests pass
- all CI checks pass
- closes PROT-104
=> PROT-104: Change env to Mainnet in GlobalSnapshotConsensusFunctionsSuite

modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverse.scala
Improved logging to get a clear error when loading snapshot failed and for which hash that happened. Used `tailRecM` in hashes chain discovery in order to not propagate the error up through the call stack failing all the enclosing invocations and making the logs impossible to read. Added log with terminal discovered hash treated as full snapshot hash.
=> Improve rollback flow and logging

modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/storage/SnapshotLocalFileSystemStorage.scala, modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/storage/SnapshotLocalFileSystemStorageSuite.scala
Currently when we try to write a snapshot we raise an error if a file exists with the hash as filename or ordinal. This PR adjusts the logic so that if the hash filename exists but the ordinal is missing we create the link instead of raising error.
=> Link snapshot file to ordinal filename if missing

build.sbt, modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Amount.scala
When executing `publishLocal` the sbt task ends due to a scaladoc error in _rosetta_, so not all the modules are published. This PR
1. Fixes the error
2. Reorders the _aggregate_ list to closer match dependencies so the error wouldn't affect publishing of required artifacts
=> Fix rosetta publish error

modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala, modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
Metagraphs that utilize the `onSnapshotConsensusResult` hook may wish to interact with additional storage and third-party APIs using a reproducible hash value. By passing the `Hashed[CurrencyIncrementalSnapshot]` we retain the original functionality without any additional imports needed during the `consumeMajorityArtifact` evaluation.
While it is possible to import the required dependencies within the data application implementations and create the needed `KryoSerializer` to produce the `Hashed[_]` value locally, this is a common use-case where boilerplate infrastructure code may be simplified by incorporation into the underlying framework. 
- modified function signature of `onSnapshotConsensusResult` to take an argument of `Hashed[CurrencyIncrementalSnapshot]` 
** work in progress **
- …
=> Enrich snapshot value passed into onSnapshotConsensusResult

.github/assets/basic_rewards_implementation.txt, .github/templates/project_template/modules/l0/src/main/scala/com/my/currency/l0/Main.scala, .github/templates/project_template/modules/l1/src/main/scala/com/my/currency/l1/Main.scala, .github/templates/project_template/project/Dependencies.scala, .github/workflows/test-metagraph-rewards.yml, .github/workflows/test-transactions.yml, modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala, modules/currency-l0/src/main/scala/org/tessellation/currency/l0/Main.scala, modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/Main.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/HttpApi.scala, modules/dag-l0/src/main/scala/org/tessellation/dag/l0/Main.scala, modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/HttpApi.scala, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala, modules/node-shared/src/main/scala/org/tessellation/node/shared/app/TessellationIOApp.scala, modules/node-shared/src/main/scala/org/tessellation/node/shared/http/routes/MetagraphRoutes.scala, modules/node-shared/src/main/scala/org/tessellation/node/shared/http/routes/NodeRoutes.scala, modules/shared/src/main/scala/org/tessellation/routes/internal.scala, modules/shared/src/main/scala/org/tessellation/schema/node.scala, modules/shared/src/main/scala/org/tessellation/schema/semver.scala
+ Adding new `metagraph/info` endpoint that can be accessed on currencyL0 and currencyL1 modules
+ Here is one print of the response
*Ignore the version of tessellation as `adding-metagraph-info`, I've hardcoded this to test on Euclid*
[PROT-567](https://constellationnetwork.atlassian.net/browse/PROT-567)
=> Adding new metagraph info endpoint

modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala, modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/HttpApi.scala, modules/node-shared/src/main/scala/org/tessellation/node/shared/http/routes/SnapshotRoutes.scala
+ Adding condition that nodes should be in READY state to allow access to fetching snapshots using SnapshotRoutes
[PROT-597](https://constellationnetwork.atlassian.net/browse/PROT-597)
=> Adding READY condition to fetch snapshots using SnapshotRoutes

modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/StateChannelBinarySender.scala, modules/currency-l0/src/test/scala/org/tessellation/currency/l0/snapshot/services/StateChannelBinarySenderSuite.scala
The issue was observed while working on different issues. Reducing the time-trigger delays on Global L0 makes producing global snapshots much faster than metagraph enqueues binaries. Such a situation can trigger the "Retry mode" when the number of pending binaries on Metagraph is lower than the initial `cap`. 
It causes the  "Retry mode" to fluctuate so it will constantly enter and exit the retry mode and reset the cap to 3 over and over. The additional condition for exiting the "Retry mode" has been introduced in that PR and unit tests are adjusted accordingly
=> Fix fluctuating retry mode when Global L0 is faster than Metagraph

build.sbt, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/dataApplication/consensus/Engine.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/DataApplicationRoutes.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/modules/Queues.scala, modules/currency-l1/src/test/scala/org/tessellation/currency/l1/DummyDataApplicationL1Service.scala, modules/currency-l1/src/test/scala/org/tessellation/currency/l1/DummyDataApplicationState.scala, modules/currency-l1/src/test/scala/org/tessellation/currency/l1/http/DataApplicationRoutesSuite.scala, modules/dag-l0/src/test/scala/org/tessellation/dag/l0/http/routes/TrustRoutesSuite.scala, modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/queue/ViewableQueue.scala, modules/node-shared/src/test/scala/org/tessellation/node/shared/domain/queue/ViewableQueueSuite.scala, modules/node-shared/src/test/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencyEventsCutterSuite.scala, modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala, modules/shared/src/main/scala/org/tessellation/ext/codecs.scala, modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala, modules/test-shared/src/main/scala/suite/HttpSuite.scala
This PR introduces a `ViewableQueue` trait and implementation in order to expose pending data updates via a `GET` public HTTP route. This work is motivated to provide a "mempool" equivalent at the metagraph layer while maintaining atomicity, minimizing changes to existing usages of `currency.l1.modules.Queues`, and reusing the available API of Cats standard `Queue`.
Additionally, smaller changes were incorporated to facilitate encoding and decoding of `DataUpdates` and  `HttpSuite` was updated to `MutableIOSuite` as the override of `Res` and `def sharedResource` were causing compilation errors.
- Updated `currencyL1` project definition to include test dependencies
- Updated usages of `dataUpdates: Queue -> ViewableQueue`
- Added `GET` route at `/data` to return the latest view of pending …
=> Viewable queue exposed in Data Application Routes

modules/wallet/src/main/scala/org/tessellation/wallet/Main.scala, modules/wallet/src/main/scala/org/tessellation/wallet/cli/method.scala
This has been tested with the following test cases:
1. One valid staking message file
2. Several identical staking messages files
3. Several valid staking message files and one with bad json (produces error)
4. Several valid staking message files and one with bad proof (produces error)
5. Several valid staking message files and one with different ordinal (produces error)
6. Several valid staking messages files with different proofs, including one which contains all proofs: result is identical to the file with all the proofs.
=> Add CLI command to merge currency message files

modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala, modules/currency-l0/src/main/scala/org/tessellation/currency/l0/StateChannel.scala, modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala, modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Rollback.scala
When we rollback an existing metagraph, and then send the snapshot fee `owner` message, the first global snapshot is set to 0 because wasn't being set before the first consensus round.
You can check the image below with some custom logs I've added to debug
I'm filling the lastGlobalSnapshot when running as rollback, I've already tested and it's working as expected
This PR was already created for the hotfix branch so we can deploy it as soon as we fix it. The DOR Metagraph in Testnet are already fixed because I've generated a custom version locally to unlock
=> Setting global snapshot after running currency rollback

modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/cli/method.scala, modules/node-shared/src/main/scala/org/tessellation/node/shared/app/TessellationIOApp.scala
+ Fixing the collateral check in currency modules to be independent of the global checker.
+ Currently, in the global layer mainnet, it's required to have 250K Tokens (DAG for the global layer and L0 Token for the currency layer). So, I've fixed this to use the CL_COLLATERAL parameter or be 0 if not provided (ONLY IN CURRENCY LAYER, THE GLOBAL LAYER KEEP WITH THE SAME BEHAVIOR)
=> Fixing collateral check in currency modules

modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/routes/CurrencyMessageRoutes.scala, modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/HttpApi.scala, modules/dag-l0/src/main/scala/org/tessellation/dag/l0/Main.scala, modules/dag-l0/src/main/scala/org/tessellation/dag/l0/domain/statechannel/StateChannelService.scala, modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Services.scala, modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Storages.scala, modules/dag-l0/src/test/scala/org/tessellation/dag/l0/domain/statechannel/StateChannelServiceSuite.scala, modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala, modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala, modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/statechannel/FeeCalculator.scala, modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/statechannel/StateChannelValidator.scala, modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencyMessageValidator.scala, modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala, modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala, modules/node-shared/src/test/scala/org/tessellation/node/shared/domain/statechannel/StateChannelValidatorSuite.scala, modules/shared/src/main/scala/org/tessellation/schema/currencyMessage.scala
+ Added new storage to store all metagraphs and fee addresses in both layers: Global and Metagraph.
+ Implemented validation in StateChannel validations to reject snapshots with existing addresses.
+ Updated the validation function to accept not only staking balances but also addresses.
+ Added new validation in StateChannel validation to reject duplicate entries.
+ Updated the current tests to ensure compatibility with the updates.
+ Added validation on the endpoint to reject existing wallets. This provides an additional layer of validation, rejecting messages of existing wallets directly at the endpoint, resulting in two layers of validation.
+ Added code to populate existing metagraphs and addresses based on the lastGlobalSnapshot, and to fill values as snapshots are accepted.
+ We …
=> Adding validations to reject repeated owner or staking address

modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/DataApplication.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/cli/method.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/dataApplication/consensus/Engine.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/domain/dataApplication/consensus/Validator.scala, modules/dag-l1/src/main/resources/application.conf, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/config/types.scala, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/Validator.scala, modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/config/DataConsensusConfig.scala
+ We had a bug that the data-l1 consensus was being stopped when the lastGlobalSnapshot wasn't present. This error was halting the streaming and blocking the node from starting the own consensus
+ I've followed the pattern of the currency layer and added a validation to the data consensus before trying to start the own consensus
It was working as expected, as the image below illustrates
=> Adding canStartOwnDataConsensus to avoid error during the data-l1 consensus and halting the streaming

build.sbt
@marcinwadon has mentioned in a couple of the example PR's that a single dependency of `tessellation-sdk` is the preferred import by metagraph projects. This PR updates the tessellation build to have the `sdk` package depend on the `currencyL1` and `currencyL0` modules.
- Updated `sdk` module definition in `build-sbt`
- Locally published updated Tessellation deps and ensured a metagraph was able to only import `tessellation-sdk` and still compile
=> Include currencyL0 and currencyL1 into sdk module

modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/DataApplicationRoutes.scala, modules/currency-l1/src/test/scala/org/tessellation/currency/l1/http/DataApplicationRoutesSuite.scala
The current implementation of the `/data` response produces a JSON array of two elements:
```
["hash","047e9423a1e6f9ee53596abf787884d007c82e1ec898a599f2048961ce5872e2"]
```
but I think the intention was to produce an object similar to the `/transactions` endpoint:
```
{"hash":"4ee922ad6b244df6ec5b84a54cb9024d92607cba3cbc2c7b283e0b2fa053cf5e"}
```
=> fix: changed /data response to match /transactions

modules/dag-l0/src/main/scala/org/tessellation/dag/l0/config/types.scala
+ Adding metanomics treasure wallets to be rewarded one time. We should mint 450M DAG, and it should be split equally between 3 wallets:
450M / 3 = 150M each
=> feat: adding treasure wallets metanomics to be one time rewarded

modules/dag-l0/src/main/scala/org/tessellation/dag/l0/config/types.scala
+ Updating one time rewards to the metanomics treasure wallets to be around 16 UTC 2024-08-08
=> fix: update epoch progress one time reward to around 16 UTC 2024-08-08

.github/templates/project_template/modules/data_l1/src/main/scala/com/my/project_template/data_l1/Main.scala, .github/templates/project_template/modules/l0/src/main/scala/com/my/project_template/l0/Main.scala, modules/currency-l1/src/test/scala/org/tessellation/currency/l1/DummyDataApplicationL1Service.scala, modules/node-shared/src/test/scala/org/tessellation/node/shared/infrastructure/snapshot/CurrencyEventsCutterSuite.scala, modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
The previous definition of `DataApplicationContextualOps` was shared between L0 and L1 services which led to metagraph developers needing to provide implementations for functions that were not invoked by the underlying `TessellationIOApp`. For example, Data-L1 nodes were forced to provide definitions for `combine` and `validateData` but these methods are only invoked for L0 nodes. This led to dummy implementations being provided simply to satisfy inheritance constraints for all Data Applications such as [Dor](https://github.com/Constellation-Labs/dor-metagraph/blob/d85e808d12bbb491fce8e789fe72f2d736cc4328/metagraph/modules/data_l1/src/main/scala/com/my/dor_metagraph/data_l1/Main.scala#L51). 
This PR introduces `SharedContextualOps, L0ContextualOps, & L1ContextualOps` to restrict the scope …
=> refactor!: restrict function scope of DataApp lifecycle methods

modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/SnapshotDownloadStorage.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/storage/SnapshotLocalFileSystemStorage.scala, modules/node-shared/src/test/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/storage/SnapshotLocalFileSystemStorageSuite.scala, modules/shared/src/main/scala/io/constellationnetwork/storage/LocalFileSystemStorage.scala
BREAKING CHANGE: Incremental snapshots would be stored by hash and ordinal in a more optimized way.
See https://github.com/Constellation-Labs/snapshot-migration for migration.
=> feat!: optimized incremental snapshot storage

modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/DataApplicationRoutes.scala, modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/EstimatedFeeResponse.scala, modules/currency-l1/src/test/scala/org/tessellation/currency/l1/DummyDataApplicationL1Service.scala, modules/currency-l1/src/test/scala/org/tessellation/currency/l1/http/DataApplicationRoutesSuite.scala, modules/shared/src/main/scala/org/tessellation/currency/schema/EstimatedFee.scala
+ Adding the `update hash` as part of the response schema of `estimate-fee` data route
+ Updated the tests to this new field and behavior
=> feat: adding update hash to the schema of estimate fee endpoint response

modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/snapshot/CurrencySnapshotConsensusStateAdvancer.scala
Invocation of `onSnapshotConsensusResult` may throw an exception due to improper error handling by the metagraph developer. If an exception is thrown the underlying consensus process enters a stalled state and the ML0 application must be restarted to recover.
- Add error handling to log the exception and return an effect for the state advancement
- Tested against a local metagraph with exceptions during `onSnapshotConsensusResult` and consensus process is no longer stalled
=> fix: catch exceptions during DataApp onSnapshotConsensusResult

modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotCreator.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotValidator.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/DataApplicationSnapshotAcceptanceManager.scala, modules/shared/src/main/scala/io/constellationnetwork/currency/dataApplication/DataApplicationTraverse.scala, modules/shared/src/main/scala/io/constellationnetwork/currency/dataApplication/package.scala, modules/shared/src/main/scala/io/constellationnetwork/currency/schema/currency.scala, modules/shared/src/main/scala/io/constellationnetwork/schema/artifact.scala, modules/shared/src/main/scala/io/constellationnetwork/schema/swap.scala
Changes
+ This ticket introduces a new field in the CIS schema: `artifacts`.
+ The `artifacts` field is of type: Option[SortedSet[SharedArtifact]].
+ SharedArtifact is a sealed trait defined in a new schema file called `artifact`.
+ Initially, the SpendTransaction class extends this trait. We have also added two additional implementations: `PendingSpendTransaction` and `ConcludedSpendTransaction`, which will now be included as artifacts in CIS.
+ I’ve moved SpendTransaction from the swap schema to the new artifact schema.
+ The DataState case class has been updated:
**Previous:**
```
case class DataState[A <: DataOnChainState, B <: DataCalculatedState](
onChain: A,
calculated: B
)
```
**Updated:**
```
case class DataState[A <: DataOnChainState, B <: DataCalculatedState](
onChain: A, …
```
=> feat: extracting spend transactions to schema

build.sbt, project/Dependencies.scala
`jsr105-api` is declared as a dependency of `dagL0` in `build.sbt`, but for some reason it's not used.
=> fix: remove javax.xml.crypto.jsr105-api

modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/snapshot/services/StateChannelBinarySender.scala, modules/currency-l0/src/test/scala/io/constellationnetwork/currency/l0/snapshot/services/StateChannelBinarySenderSuite.scala
Previously we were removing confirmed binaries from the tracking queue. Now we need to keep them together with confirmation proof (the reference to Global Snapshot in which binary was confirmed)
=> feat: keep binaries confirmed in global snapshot with confirmation proof

modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/StateChannel.scala, modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/cli/method.scala, modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/config/types.scala, modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/modules/HttpApi.scala, modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/modules/Programs.scala, modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/modules/Services.scala, modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/modules/Storages.scala, modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/snapshot/storage/LastNGlobalSnapshotStorage.scala
Regardless of the chosen solution (fixed window / consensus) for selecting the GIS to return as the 'synchronized' one, we need to keep the last N GlobalSnapshots instead of just the latest one. It should also allow for the deletion of stored GIS that are below the 'synchronized' one.
=> feat: keep last N global snapshots in storage for Currency L0

modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/CurrencyL0App.scala, modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/modules/Services.scala, modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/node/L0NodeContext.scala, modules/shared/src/main/scala/io/constellationnetwork/currency/dataApplication/package.scala, modules/shared/src/main/scala/io/constellationnetwork/schema/address.scala, modules/shared/src/main/scala/io/constellationnetwork/schema/artifact.scala, modules/shared/src/main/scala/io/constellationnetwork/schema/swap.scala
+ Additional parts that should be used by amm metagraph, such as:
-> getMetagraphId: We will use this to get the AllowSpends aggregated in GlobalSnapshotInfo to the current metagraph
-> allowSpend - currency: Changed to optional since we need it as none to represent DAG
-> ordering: adding ordering to the missing parts that we need in amm metagraph
=> feat: adding features required by amm metagraph

modules/shared/src/main/scala/io/constellationnetwork/schema/artifact.scala, modules/shared/src/main/scala/io/constellationnetwork/schema/swap.scala
* Update Artifacts to Use List[SpendAction]: Modified the artifact structure to use List[SpendAction] instead of List[SpendTransaction], aligning with recent updates in the Notion documentation.
* SpendAction as Atomic Action:
* Input (SpendTransaction): Represents the user’s input, such as the primary declared currency for staking or the “Allow spend” transaction.
* Output (SpendTransaction): Represents the AMM’s output, either as “spending” funds or the staking pair currency determined by the AMM.
* Updated Functionality: Now sending a SpendAction instead of a single SpendTransaction to reflect the new schema requirements.
=> feat: moving SpendAction and update it to extend SharedArtifact instead of SpendTransaction

modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/cluster/programs/Joining.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/cluster/services/Cluster.scala, modules/shared/src/main/scala/io/constellationnetwork/schema/peer.scala, modules/shared/src/test/scala/io/constellationnetwork/schema/generators.scala
Returns clusterSession on each node reported in "cluster/info". Required by https://github.com/Constellation-Labs/cllb/pull/18
=> feat: add cluster session to PeerInfo

.github/workflows/release-apidocs.yml
run release-apidocs only when there's a change in the docs
=> chore: run publish only on doc/api changes

modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/app/TessellationIOApp.scala, modules/shared/src/main/scala/io/constellationnetwork/env/JarSignature.scala
When running inside intelliJ, there's no jar to hash and the calculation fails. This PR gives a default value if no jar and running from dev environment, if there's no jar and the env is not dev, it fails.
=> fix: skip jar hash if running directly from classes

modules/shared/src/main/scala/io/constellationnetwork/schema/address.scala, modules/shared/src/main/scala/io/constellationnetwork/security/Hash.scala, modules/shared/src/test/scala/io/constellationnetwork/security/HashSuite.scala
This PR deprecates the Guava version of `Hash.fromBytes()` method. 
It doesn't remove Guava from the dependency list, and provides compatibility tests.
=> refactor: deprecate Guava

.github/workflows/release-apidocs.yml
restore the trigger on PR so terraform execution can be validated against the doc changes without waiting to the merge
=> fix: restore trigger on PR

.github/action_scripts/send_transactions/data-with-fee.js, modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/DataApplication.scala, modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/domain/dataApplication/consensus/Engine.scala, modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/http/DataApplicationRoutes.scala, modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/modules/HttpApi.scala, modules/currency-l1/src/test/scala/io/constellationnetwork/currency/l1/http/DataApplicationRoutesSuite.scala, modules/dag-l1/src/main/scala/io/constellationnetwork/dag/l1/GlobalSnapshotAlignment.scala, modules/shared/src/main/scala/io/constellationnetwork/currency/dataApplication/package.scala
+ Changing the serializer of feeTxn to use the same as AllowSpends, TokenLocks, and CurrencyTxn. All these transactions use brotli, so I've added brotli to feeTxn as well, so we can have all in the same pattern
=> feat: adding brotli serialization for fee transactions

modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/modules/Services.scala, modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala, modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala, modules/dag-l1/src/test/scala/io/constellationnetwork/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotValidator.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/modules/SharedServices.scala
+ Adding a flag to disable the validation of artifacts on `createContext` function, used by BlockExplorer
=> feat: adding a flag to skip artifact validation in currency incremental snapshots

modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/cli/method.scala, modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/modules/Services.scala, modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/cli/method.scala, modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotConsensus.scala, modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala, modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala, modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala, modules/dag-l1/src/test/scala/io/constellationnetwork/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala, modules/node-shared/src/main/resources/application.conf, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/cli/CliMethod.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/config/types.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotValidator.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/modules/SharedServices.scala
+ The new globalSyncView will break for traversing historical snapshots when rolling back since we fetch the missing global snapshots directly from the peers. So, I'm disabling the validation of this field, such as we did with dataAppplication (I think?)
=> fix: adding new config fields-added-ordinals on config to read historical snapshots

.github/workflows/setup-environment.yml, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotCreator.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala
+ Since spendActions is a field in the snapshot schema, and we do not aggregate, if we skip on ordinal between lastGlobalView and lastSyncGlobalSnapshot, we have a chance to miss the spend actions. 
+ This PR aims to get all spend actions between this interval
=> fix: fixing CurrencySnapshotAcceptanceManager

modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/swap/AllowSpendValidator.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
+ Some metagraphs can be offline for a long period and have the globalView filled.
This PR aims not to allow fetching more than 20 snapshots per metagraph to not slow the network
=> feat: adding a security check to not fetch more than 20 snapshots to search spendTxns

.github/action_scripts/node_parameters/node_parameters.js, modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/http/routes/NodeParametersRoutes.scala, modules/shared/src/main/scala/io/constellationnetwork/schema/delegatedStake.scala
/node-params endpoint now shows information about all available nodes, even if the node is not in a cluster (basic information shows then only)
=> fix: node-params endpoint shows all avaialble nodes

modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/CurrencyL1App.scala, modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/modules/HttpApi.scala, modules/currency-l1/src/test/scala/io/constellationnetwork/currency/l1/domain/snapshots/programs/CurrencySnapshotProcessorSuite.scala, modules/currency-l1/src/test/scala/io/constellationnetwork/currency/l1/http/TokenLockRoutesSuite.scala, modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/infrastructure/rewards/GlobalDelegatedRewardsDistributor.scala, modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/modules/Programs.scala, modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/rewards/GlobalDelegatedRewardsDistributorSuite.scala, modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala, modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala, modules/dag-l1/src/main/scala/io/constellationnetwork/dag/l1/Main.scala, modules/dag-l1/src/main/scala/io/constellationnetwork/dag/l1/modules/HttpApi.scala, modules/dag-l1/src/test/scala/io/constellationnetwork/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala, modules/node-shared/src/main/resources/application.conf, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/config/types.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/tokenlock/TokenLockValidator.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/http/routes/TokenLockRoutes.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/DelegatedRewardsDistributor.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala, modules/shared/src/main/scala/io/constellationnetwork/currency/dataApplication/package.scala, modules/shared/src/main/scala/io/constellationnetwork/schema/GlobalSnapshot.scala
* Added `max-token-locks-per-address` and `min-token-lock-amount` parameters to application.config.
* These parameters will initially be used only on the DAG layer. However, since they are defined as `Option` types (with None provided for the currency layer), we can easily enable them for the currency layer in the future if needed.
* Introduced a new validation function in the existing TokenLocks validation file. This new validation checks the number of active token locks, which requires access to the latest state via lastSnapshotStorage. The function is invoked in the POST endpoint and also triggers the existing validations.
* Refactored the delegateRewards field to use `Map[PeerId, Map[Address, Amount]]` instead of `Map[Address, Map[PeerId, Amount]]` for improved structure and clarity. …
=> feat: adding delegated stake min amount and max number validations

modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/DelegatedRewardsDistributor.scala
+ Changing the wrong merging maps that were overriding the active delegated stakes
+ I've tested locally, and on the images below, we can confirm:
Same rewards accruing rewards in both delegations
Same address with 2 delegations
After changing the delegation to another nodeId the rewards are kept
=> feat: changing from ++ to |+| when combining active delegated stakes

.github/workflows/release.yml
Adds `id` to the step in the build job which creates the release tag. This needs to be set to correctly pass the variable between jobs
=> fix: pass release tag between jobs

modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/config/DelegatedRewardsConfigProvider.scala, modules/node-shared/src/main/resources/application.conf
Updates rewards config values impacted by scaling of epoch progress from 43 sec to 65 sec
=> chore: update epoch progress configs

modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/modules/Programs.scala, modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/snapshot/programs/Download.scala, modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/DataApplicationSnapshotAcceptanceManager.scala
+ This PR aims to fix the forking issue with currency L0.
+ After investigation, I've noticed 2 inconsistencies on the  code:
1st -> We were validating the same state to all blocks, and we were validating all blocks/updates at once. So I've fixed this part
2nd -> We were missing the lastCurrencySnapshot to validator nodes joining the network. In some metagraphs, such as DO,R we use this information to combine, and if we don't have this, when we join the consensus, we produce inconsistent artifacts
=> fix: validating state per block and setting last currency snapshot
