Constellation-Labs/tessellation

modules/core/src/test/scala/org/tessellation/trust/DataGenerationSuite.scala
modules/core/src/test/scala/org/tessellation/trust/DataGenerator.scala

Preparation for sybil attack example next, verify data generator
is still working properly and generating proper edges.

Update data generator to new cats, add basic test.

---

modules/core/src/main/scala/org/tessellation/infrastructure/trust/DATT.scala
modules/core/src/test/scala/org/tessellation/trust/SybilAttackSuite.scala
modules/core/src/test/scala/org/tessellation/trust/TrustCalculationSuite.scala

Basic test covering weighted and non-weighted edges.
Update sybil attack to use non-malicious node in calculation
of defense factor

Directed Acylic Transitive Trust implementation

---

build.sbt
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/config/TipsConfig.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/BlockService.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/block/Tips.scala
modules/dag-shared/src/main/scala/org/tessellation/dag/block/BlockValidator.scala
modules/dag-shared/src/main/scala/org/tessellation/dag/domain/block/BlockReference.scala
modules/dag-shared/src/main/scala/org/tessellation/dag/domain/block/DAGBlock.scala

Review the block service part only

DAG state channel block service

---

modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala

Fix to a @kpudlik comment from #203

Use `MaybeState` type alias

---

examples/simple-snapshot-publisher/src/main/scala/org/example/GenerateInputApp.scala
modules/core/src/main/scala/org/tessellation/Main.scala
modules/core/src/main/scala/org/tessellation/infrastructure/aci/StateChannelInstanceLoader.scala
modules/core/src/main/scala/org/tessellation/package.scala
modules/core/src/test/scala/org/tessellation/domain/aci/StateChannelOutputGistedSuite.scala
modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorageSuite.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/package.scala
modules/dag-shared/src/main/scala/org/tessellation/dag/package.scala
modules/kernel/src/main/scala/org/tessellation/kernel/package.scala
modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
modules/shared/src/main/scala/org/tessellation/ext/kryo.scala
modules/shared/src/main/scala/org/tessellation/kryo/KryoSerializer.scala
modules/shared/src/main/scala/org/tessellation/shared/package.scala
modules/shared/src/test/scala/org/tessellation/kryo/KryoSerializerSuite.scala
modules/shared/src/test/scala/org/tessellation/schema/TransactionSuite.scala

https://constellationnetwork.atlassian.net/browse/CONST-421

Validation of kryo registration IDs.

---

modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStorage.scala
modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/SnapshotOrdinal.scala

Tested manually as creating unit tests wasn't so simple for this case. When I will be happy with the unit tests quality I will create a separate PR for them ;).

Keep snapshot in memory when offloading fails

---

modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/Routes.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Daemons.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensus.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/HealthCheckConsensusRound.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/HealthCheckRoundId.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/healthcheck/consensus/types/types.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/GossipDaemon.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala
modules/sdk/src/main/scala/org/tessellation/sdk/package.scala

Mainly:
- register missing kryo classes
- more verbose logging
- trigger ping healthcheck on gossip error

Fix healthcheck

---

CONTRIBUTING.md
SETUP.md

Added guides for how to set-up an environment, how to use SBT in the command line, and how to contribute to the project.
TODO: Add instructions for setting up IntelliJ.

Added a Setup and Contributing guide.

---

skaffold.yaml

This enables cross-platform build

Add platform to docker build command

---

modules/dag-l1/src/main/scala/org/tessellation/dag/l1/infrastructure/healthcheck/HealthCheckDaemon.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/Daemons.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/modules/HttpApi.scala

Add missing daemon driving the healthcheck consensuses management.
Add missing endpoint for checking node's health.

Fix ping healthcheck on L1

---

modules/core/src/main/scala/org/tessellation/cli/method.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/cli/method.scala
modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/healthcheck/ping/PingHealthCheckConsensus.scala

Ping healthcheck on L0 is disabled, enabled on L1

Ping healthcheck can be explicitly enabled/disabled

---

kubernetes/grafana/dashboards/tessellation.json
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/metrics/Metrics.scala

Metrics and dashboards for:
* consensus duration
* proposal affinity

Consensus metrics for duration and proposal affinity

---

kubernetes/grafana/dashboards/tessellation.json

L0 & L1 uptime panels

---

modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
modules/dag-shared/src/main/scala/org/tessellation/dag/snapshot/GlobalSnapshot.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusState.scala
modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala

**IMPORTANT!**
This change is a breaking change for testnet and will require full restart (from genesis) on testnet.
**However, it is not a breaking change for mainnet.**

Store signature of SCSnapshot in GlobalSnapshot

---

modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/dag/metadataSchema.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/dag/schema.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/search/OperationStatus.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/search/Operator.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/server/model/search/SearchTransactionRequest.scala

Added the intermediary models needed to hold the parameters for the Rosetta `search` endpoints ([link](https://www.rosetta-api.org/docs/SearchApi.html)).

Added the models for the search endpoint

---

modules/dag-l1/src/main/scala/org/tessellation/dag/l1/domain/consensus/block/BlockConsensusCell.scala

There is only a change in indentation but GH can't pick it up correctly.

Format BlockConsensusCell class properly

---

modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/consensus/block/RoundDataSuite.scala
modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/transaction/TransactionStorageSuite.scala
modules/dag-shared/src/test/scala/org/tessellation/dag/transaction/TransactionGenerator.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/TransactionIdentifier.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionHash.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/ConstructionError.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/RosettaError.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala

Added Rosetta's [`construction/hash` endpoint](https://www.rosetta-api.org/docs/ConstructionApi.html#constructionhash).

Rosetta - Added the construction hash endpoint.

---

modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Amount.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Currency.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Operation.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionPreprocess.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala
modules/shared/src/main/scala/org/tessellation/schema/package.scala

Added Rosetta's [`construction/preprocess` endpoint](https://www.rosetta-api.org/docs/ConstructionApi.html#constructionpreprocess).

Added construction preprocess endpoint.

---

modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Amount.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Currency.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionParse.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala

Added Rosetta's [`construction/parse` endpoint](https://www.rosetta-api.org/docs/ConstructionApi.html#constructionparse).

Added Rosetta's construction parse endpoint.

---

modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/RosettaPublicKey.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/RosettaSignature.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionCombine.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/ConstructionError.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/RosettaError.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala

Added Rosetta's [`construction/combine` endpoint](https://www.rosetta-api.org/docs/ConstructionApi.html#constructioncombine).

Added Rosetta's construction/combine endpoint.

---

modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/AccountIdentifier.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Amount.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Currency.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/Operation.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/RosettaSignature.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionMetadata.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/api/construction/ConstructionPayloads.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/construction/ConstructionService.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/ConstructionError.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/domain/error/RosettaError.scala
modules/rosetta/src/main/scala/org/tessellation/rosetta/http/routes/ConstructionRoutes.scala
modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/construction/ConstructionServiceSuite.scala
modules/rosetta/src/test/scala/org/tessellation/rosetta/domain/generators.scala
modules/shared/src/main/scala/org/tessellation/schema/transaction.scala
modules/shared/src/main/scala/org/tessellation/security/Hash.scala
modules/shared/src/main/scala/org/tessellation/security/signature/signature.scala
modules/wallet/src/main/scala/org/tessellation/wallet/transaction/package.scala

Implement rosetta payloads endpoint

Implement payloads endpoint

---

modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Genesis.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Rollback.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusManager.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusHandler.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusManager.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/genesis/Loader.scala

…atible with onion architecture

Remove infrastructure dependency from Rollback and Genesis

---

SETUP.md

Corrected the `skaffold dev` command in the docs

Corrected skaffold dev command in docs

---

modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/PeerSelect.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/MajorityPeerSelect.scala
modules/shared/src/main/resources/logback-included.xml

Logging the peer selection process

Added logging to peer selection.

---

modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/Main.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/P2PClient.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/P2PClient.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/storage/SnapshotStorage.scala
modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/SdkP2PClient.scala
modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/L0GlobalSnapshotClient.scala
modules/sdk/src/main/scala/org/tessellation/sdk/http/routes/SnapshotRoutes.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/MajorityPeerSelect.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/storage/SnapshotStorage.scala

Added an endpoint to get the hash of a `Snapshot` given a `SnapshotOrdinal`.

Added endpoint to get Snapshot hash

---

modules/currency-l0/src/main/scala/org/tessellation/currency/l0/Main.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cell/L0Cell.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Daemons.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Queues.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensus.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotEventsPublisherDaemon.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/package.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Genesis.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
modules/shared/src/main/scala/org/tessellation/currency/dataApplication.scala
modules/shared/src/main/scala/org/tessellation/currency/schema/currency.scala

Here is an up-to-date complete and working example:
```scala
object Acme {
@derive(decoder, encoder)
sealed trait Usage extends DataUpdate {
val value: Long
}
@derive(decoder, encoder)
case class EnergyUsage(value: Long) extends Usage
@derive(decoder, encoder)
case class WaterUsage(value: Long) extends Usage
@derive(decoder, encoder)
case class State(totalEnergyUsage: Long, totalWaterUsage: Long) extends DataState
case object EnergyNotPositive extends DataApplicationValidationError {
val message = "energy ussage must be positive"
}
case object WaterNotPositive extends DataApplicationValidationError {
val message = "water ussage must be positive"
}
case object Noop extends DataApplicationValidationError {
val message = "invalid update"
}
val energy: DataApplicationL0Service[IO, Usage, …
```

DataApplication implementation for Currency L0

---

modules/core/src/main/scala/org/tessellation/http/routes/TrustRoutes.scala
modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/http/p2p/P2PClient.scala
modules/currency-l1/src/main/scala/org/tessellation/currency/l1/http/p2p/P2PClient.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/http/p2p/P2PClient.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/PeerSelect.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/OrdinalTrustMap.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/PublicTrustMap.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/TrustMap.scala
modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/L0TrustClient.scala
modules/sdk/src/main/scala/org/tessellation/sdk/http/p2p/clients/TrustClient.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/MajorityPeerSelect.scala
modules/shared/src/main/scala/org/tessellation/schema/peer.scala
modules/shared/src/main/scala/org/tessellation/schema/trust.scala

Exposed trust values to non-core services

Exposed trust values to non-core services

---

.github/workflows/test-metagraph-rewards.yml
.github/workflows/test-transactions.yml

Changing metagraph dependencies generation in action

Changing metagraph dependencies generation in action

---

modules/core/src/main/scala/org/tessellation/http/routes/TrustRoutes.scala
modules/core/src/main/scala/org/tessellation/infrastructure/trust/storage/TrustStorage.scala
modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala
modules/core/src/main/scala/org/tessellation/modules/Programs.scala
modules/core/src/test/scala/org/tessellation/http/routes/TrustRoutesSuite.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Programs.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/PeerSelect.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/TrustStorage.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/PeerSelect.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/WeightedProspect.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/WeightedSampling.scala
modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/WeightedProspectSuite.scala
modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/WeightedSamplingSuite.scala

Peer selection takes trust value into account

Peer selection takes trust value into account

---

modules/core/src/main/scala/org/tessellation/cli/method.scala
modules/core/src/main/scala/org/tessellation/config/types.scala
modules/core/src/main/scala/org/tessellation/modules/Daemons.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/config/types.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Daemons.scala
modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/PeerDiscoveryDelay.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/PeerSelect.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/daemon/DownloadDaemon.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/daemon/SelectablePeerDiscoveryDelay.scala

Delay download until a selectable peer is found

Delay download until a selectable peer is found

---

modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotCreator.scala
modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala

It's expected that the metagraph implementations modify their implementation of `combine` to support receiving `List` instead of `NonEmptyList`

Always call combine when creating proposal artifact

---

modules/core/src/main/scala/org/tessellation/cli/method.scala
modules/core/src/main/scala/org/tessellation/config/types.scala
modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
modules/core/src/main/scala/org/tessellation/infrastructure/trust/storage/TrustStorage.scala
modules/core/src/main/scala/org/tessellation/modules/Services.scala
modules/core/src/main/scala/org/tessellation/modules/Storages.scala
modules/core/src/test/scala/org/tessellation/infrastructure/trust/storage/TrustStorageSuite.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/config/types.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensus.scala
modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/seedlist.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/snapshot/ProposalSelect.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/trust/storage/TrustStorage.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/Consensus.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/PeerSelect.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/ProposalOccurrenceSelect.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/ProposalSelectWithFallback.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/ProposalTrustSelect.scala
modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/ProposalOccurrenceSelectSuite.scala
modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/ProposalSelectWithFallbackSuite.scala
modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/ProposalTrustSelectSuite.scala
modules/shared/src/main/scala/org/tessellation/schema/trust.scala

Use trust scores in peer declarations selection

Use trust scores in peer declarations selection

---

modules/core/src/main/scala/org/tessellation/cli/method.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala

Changed min. peers for selection to 1.

Changed min. peers for selection to 1.

---

CONTRIBUTING.md

closes #747 (unsquased to simplify review)
Would need a few more passes (as usual with docs/writing, this can take time, so usually would go into separate PR).
(please feel free to close this PR for any reason. All good here)

747 update contrib

---

modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
modules/core/src/test/scala/org/tessellation/domain/statechannel/StateChannelValidatorSuite.scala
modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/cli/method.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/config/types.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
modules/sdk/src/main/scala/org/tessellation/sdk/app/TessellationIOApp.scala
modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/block/processing/BlockNotAcceptedReason.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/consensus/ConsensusFunctions.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/statechannel/StateChannelValidator.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/consensus/ConsensusStateUpdater.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencyEventsCutter.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotContextFunctions.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotCreator.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotValidator.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/DataApplicationSnapshotAcceptanceManager.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/SnapshotConsensusFunctions.scala
modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkServices.scala
modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkValidators.scala
modules/sdk/src/main/scala/org/tessellation/sdk/package.scala
modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencyEventsCutterSuite.scala
modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/snapshot/CurrencySnapshotCreatorSuite.scala
modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala
modules/shared/src/test/scala/org/tessellation/schema/generators.scala

First https://github.com/Constellation-Labs/tessellation/pull/744

Recursively limit proposal size by returning excess blocks back to pool

---

modules/core/src/main/scala/org/tessellation/modules/HttpApi.scala

Enable state channel public routes
- Removed flag checking environment in `HttpApi`
- Unit test passing
- CI passed
- PROT-464

Enable state channel public routes

---

.github/workflows/test-metagraph-rewards.yml
.github/workflows/test-transactions.yml

Updating action

---

modules/core/src/main/scala/org/tessellation/Main.scala
modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensus.scala
modules/core/src/main/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
modules/core/src/test/scala/org/tessellation/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/CurrencyL0App.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensus.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusFunctions.scala
modules/currency-l1/src/main/scala/org/tessellation/currency/l1/CurrencyL1App.scala
modules/dag-l1/src/main/scala/org/tessellation/dag/l1/Main.scala
modules/sdk/src/main/scala/org/tessellation/sdk/cli/CliMethod.scala
modules/sdk/src/main/scala/org/tessellation/sdk/config/types.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/fork/ForkDetect.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/fork/ForkInfo.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/fork/ForkInfoEntries.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/fork/ForkInfoMap.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/fork/ForkInfoStorage.scala
modules/sdk/src/main/scala/org/tessellation/sdk/domain/fork/StoredForkInfo.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/fork/ForkDetect.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/fork/ForkInfoHandler.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/fork/ForkInfoStorage.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/gossip/RumorHandlers.scala
modules/sdk/src/main/scala/org/tessellation/sdk/infrastructure/snapshot/SnapshotConsensusFunctions.scala
modules/sdk/src/main/scala/org/tessellation/sdk/modules/SdkStorages.scala
modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/fork/ForkDetectSuite.scala
modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/fork/ForkInfoHandlerSuite.scala
modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/fork/ForkInfoStorageSuite.scala
modules/sdk/src/test/scala/org/tessellation/sdk/infrastructure/fork/generators.scala

Added fork info handler and storage.

Added fork info handler and storage

---

modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/cluster/programs/Joining.scala
modules/node-shared/src/main/scala/org/tessellation/node/shared/modules/SharedPrograms.scala

Joining & peer discovery finishes completely before unlocking download

Joining & peer discovery finishes before download

---

modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Services.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensus.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusStateAdvancer.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/CurrencySnapshotConsensusStateCreator.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/programs/Genesis.scala
modules/currency-l0/src/main/scala/org/tessellation/currency/l0/snapshot/services/StateChannelSnapshotService.scala
modules/dag-l0/src/main/scala/org/tessellation/dag/l0/domain/statechannel/StateChannelService.scala
modules/dag-l0/src/main/scala/org/tessellation/dag/l0/http/routes/StateChannelRoutes.scala
modules/dag-l0/src/main/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotConsensusStateCreator.scala
modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/HttpApi.scala
modules/dag-l0/src/test/scala/org/tessellation/dag/l0/domain/statechannel/StateChannelServiceSuite.scala
modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
modules/dag-l1/src/test/scala/org/tessellation/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
modules/node-shared/src/main/resources/application.conf
modules/node-shared/src/main/scala/org/tessellation/node/shared/app/TessellationIOApp.scala
modules/node-shared/src/main/scala/org/tessellation/node/shared/cli/CliMethod.scala
modules/node-shared/src/main/scala/org/tessellation/node/shared/config/types.scala
modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/statechannel/FeeCalculator.scala
modules/node-shared/src/main/scala/org/tessellation/node/shared/domain/statechannel/StateChannelValidator.scala
modules/node-shared/src/main/scala/org/tessellation/node/shared/ext/pureconfig/pureconfig.scala
modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/consensus/PeerDeclarations.scala
modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/consensus/declaration.scala
modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessor.scala
modules/node-shared/src/main/scala/org/tessellation/node/shared/modules/SharedValidators.scala
modules/node-shared/src/test/scala/org/tessellation/node/shared/domain/statechannel/FeeCalculatorSuite.scala
modules/node-shared/src/test/scala/org/tessellation/node/shared/domain/statechannel/StateChannelValidatorSuite.scala
modules/shared/src/main/scala/org/tessellation/schema/currencyMessage.scala

I plan to add couple of simple unit tests for the fee calculator but other than that this PR is ready for review.
UPDATE: tests added
FYI we will need to set the configurations for every env before deploying.

Calculate and validate minimal metagraph fee

---

modules/node-shared/src/main/resources/application.conf

+ Updating the testnet network fee configuration

Updating testnet fees configuration

---

modules/shared/src/main/scala/org/tessellation/currency/dataApplication/package.scala

This corrects how `extractFees` was introduced to the data application layer

Adjust location of extractFees in Data Application traits

---

modules/currency-l0/src/main/scala/org/tessellation/currency/l0/modules/Storages.scala
modules/dag-l0/src/main/scala/org/tessellation/dag/l0/Main.scala
modules/dag-l0/src/main/scala/org/tessellation/dag/l0/infrastructure/snapshot/programs/RollbackLoader.scala
modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Programs.scala
modules/dag-l0/src/main/scala/org/tessellation/dag/l0/modules/Storages.scala
modules/dag-l0/src/test/scala/org/tessellation/dag/l0/infrastructure/snapshot/SnapshotStorageSuite.scala
modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/storage/SnapshotInfoLocalFileSystemStorage.scala
modules/node-shared/src/main/scala/org/tessellation/node/shared/infrastructure/snapshot/storage/SnapshotLocalFileSystemStorage.scala
modules/node-shared/src/test/scala/org/tessellation/node/shared/infrastructure/snapshot/storage/SnapshotLocalFileSystemStorageSuite.scala
modules/shared/src/main/scala/org/tessellation/currency/dataApplication/storage/TraverseLocalFileSystemTempStorage.scala
modules/shared/src/main/scala/org/tessellation/security/signature/Signed.scala
modules/shared/src/main/scala/org/tessellation/storage/LocalFileSystemStorage.scala
modules/tools/src/main/scala/org/tessellation/tools/Main.scala

Use fallback class for Kryo deserialization of GlobalSnapshotInfo

Fix GlobalSnapshotInfo storage

---

.github/action_scripts/send_transactions/data.js
.github/templates/project_template/modules/l0/src/main/scala/com/my/project_template/l0/custom_routes/CustomRoutes.scala

+ Adding custom endpoint to search by address and return not found in case of failure
It works as expected

Fix test data-transaction action

---

.commitlintrc
.github/workflows/pr-commits.yml
.gitignore
.husky/commit-msg
flake.nix
package-lock.json
package.json

To configure local hook for commit name linting:
1. Install `npm`,
2. Run `npm install` to install packages,
3. Run `npx husky`.

ci: action for linting commit names and optional local hook

---

modules/test-shared/src/main/scala/suite/HttpSuite.scala

chore: remove redundant quotes in HttpSuite

---

modules/shared/src/main/scala/io/constellationnetwork/currency/schema/currency.scala
modules/shared/src/main/scala/io/constellationnetwork/schema/swap.scala

+ Adding spendTransactions to the CurrencySnapshot schema
+ Updated field names to match notion doc

feat: adding spend transactions to currency incremental snapshot schema

---

modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/CurrencyL0App.scala
modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/cli/method.scala
modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/modules/Services.scala
modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/modules/Validators.scala
modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/CurrencyL1App.scala
modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/cli/method.scala
modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/config/types.scala
modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/modules/Services.scala
modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/rewards/RewardsSuite.scala
modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
modules/dag-l1/src/main/scala/io/constellationnetwork/dag/l1/Main.scala
modules/dag-l1/src/main/scala/io/constellationnetwork/dag/l1/modules/Validators.scala
modules/dag-l1/src/test/scala/io/constellationnetwork/dag/l1/domain/consensus/block/RoundDataSuite.scala
modules/dag-l1/src/test/scala/io/constellationnetwork/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
modules/node-shared/src/main/resources/application.conf
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/app/TessellationIOApp.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/cli/CliMethod.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/config/types.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/transaction/TransactionValidator.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/ext/pureconfig/pureconfig.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/services/AddressService.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/modules/SharedValidators.scala

Changes: move locked addresses from TransactionValidator to application.,conf

feat:  move locked addresses to config

---

.github/workflows/release.yml
.github/workflows/testnet-release.yml

Add signed sh256 hash of release jar to git workflow.

feat: add sha256 signature of release

---

build.sbt
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/app/TessellationIOApp.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/cluster/programs/Joining.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/cluster/services/Cluster.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/modules/SharedServices.scala
modules/shared/src/main/scala/io/constellationnetwork/env/JarSignature.scala
modules/shared/src/main/scala/io/constellationnetwork/schema/peer.scala
modules/shared/src/test/scala/io/constellationnetwork/env/JarSignatureSuite.scala
modules/shared/src/test/scala/io/constellationnetwork/schema/generators.scala

calculate fat jar hash during startup and report it in cluster data

feat: include jar hash in peer metadata

---

.github/workflows/release-apidocs.yml

A PR shouldn't trigger publishing documentation.

fix: remove trigger on PR

---

modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/CurrencyL1App.scala
modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/domain/snapshot/programs/CurrencySnapshotProcessor.scala
modules/dag-l1/src/main/scala/io/constellationnetwork/dag/l1/Main.scala
modules/dag-l1/src/main/scala/io/constellationnetwork/dag/l1/domain/snapshot/programs/DAGSnapshotProcessor.scala
modules/dag-l1/src/main/scala/io/constellationnetwork/dag/l1/domain/snapshot/programs/SnapshotProcessor.scala
modules/dag-l1/src/test/scala/io/constellationnetwork/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/swap/block/AllowSpendBlockStorage.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/tokenlock/block/TokenLockBlockStorage.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/modules/SharedValidators.scala
modules/shared/src/main/scala/io/constellationnetwork/currency/schema/currency.scala

+ This PR adds the majority alignment for token locks
+ I'm pointing the PR to the majority alignment branch that introduces the majority alignment to allow spends and also solves some issues with Kryo
+ I've also cleaned some unused parts from the majority-alignment branch

feat: token lock majority alignment

---

.github/workflows/test-currency-transactions.yml
.github/workflows/test-data-transactions.yml
.github/workflows/test-metagraph-rewards.yml

Upgrade upload-artifact action from v3 to v4 ( see https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/ )

chore: upgrade GH upload action

---

modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/CurrencyL0App.scala
modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/cli/method.scala
modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/CurrencyL1App.scala
modules/currency-l1/src/main/scala/io/constellationnetwork/currency/l1/cli/method.scala
modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/Main.scala
modules/dag-l1/src/main/scala/io/constellationnetwork/dag/l1/Main.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/app/TessellationIOApp.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/cli/CliMethod.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/config/types.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/modules/SharedPrograms.scala

For discussion on this change, please see #1002

fix: revert changes to SharedConfig via config arg in IO app constr

---

modules/dag-l1/src/main/scala/io/constellationnetwork/dag/l1/domain/snapshot/programs/DAGSnapshotProcessor.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/storage/LastNGlobalSnapshotStorage.scala

+ Adding last n global snapshot sync to dag-l1

feat: adding last n global snapshot sync to dag-l1

---

.github/action_scripts/check_clusters/dag.js
.github/action_scripts/check_clusters/metagraph-data.js
.github/action_scripts/send_transactions/allow-spends-and-spend-transactions.js
.github/action_scripts/shared/network.js
.github/action_scripts/shared/operations.js
.github/templates/actions/hypergraph/dag_l1/dl1_cluster/action.yml
.github/templates/actions/hypergraph/setup/action.yml
.github/templates/actions/hypergraph/start/action.yml
.github/templates/actions/metagraph/data_l1/dl1_cluster/action.yml
.github/templates/actions/metagraph/setup/action.yml
.github/templates/actions/metagraph/start/action.yml
.github/workflows/test-allow-spends-and-spend-transactions.yml

- check doubled allow spend transactions
- check expired allow spend
- verify spend balances
- double use allow spend workflow

test: verify spend balances

---

.github/action_scripts/send_transactions/token-locks.js
modules/currency-l1/src/test/scala/io/constellationnetwork/currency/l1/http/TokenLockRoutesSuite.scala
modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotConsensusFunctions.scala
modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotTraverse.scala
modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/SnapshotDownloadStorage.scala
modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/domain/statechannel/StateChannelServiceSuite.scala
modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotStateChannelEventsProcessorSuite.scala
modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotTraverseSuite.scala
modules/dag-l1/src/test/scala/io/constellationnetwork/dag/l1/domain/snapshot/programs/SnapshotProcessorSuite.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/tokenlock/ContextualTokenLockValidator.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/tokenlock/TokenLockStorage.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/tokenlock/block/TokenLockBlockAcceptanceLogic.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/tokenlock/filter/Consecutive.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/CurrencySnapshotAcceptanceManager.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/GlobalSnapshotContextFunctions.scala
modules/shared/src/main/scala/io/constellationnetwork/merkletree/MerkleTreeValidator.scala
modules/shared/src/main/scala/io/constellationnetwork/schema/GlobalSnapshot.scala
modules/shared/src/main/scala/io/constellationnetwork/schema/tokenLock.scala
modules/shared/src/test/scala/io/constellationnetwork/merkletree/MerkleTreeValidatorSuite.scala
modules/shared/src/test/scala/io/constellationnetwork/schema/generators.scala

I've also tested rolling back with snapshots from testnet and it worked normally

feat: adding artifacts field to GIS schema

---

.github/action_scripts/send_transactions/allow-spends-and-spend-transactions.js
.github/workflows/test-allow-spends.yml
.github/workflows/test-spend-transactions.yml
build.sbt
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/swap/AllowSpendValidator.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/swap/SpendActionValidator.scala

- test: invalid currency id workflow
- test: exceeding allow spend amount
- test: uncomment balance verification after spend transaction
- test: wrong approver workflow

test: allow spend and spend transaction checks

---

doc/api/models/schemas/CreateDelegatedStake.yml
doc/api/models/schemas/CreateNodeCollateral.yml
doc/api/models/schemas/WithdrawDelegatedStake.yml
doc/api/models/schemas/WithdrawNodeCollateral.yml
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/delegatedStake/UpdateDelegatedStakeValidator.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/nodeCollateral/UpdateNodeCollateralValidator.scala
modules/node-shared/src/test/scala/io/constellationnetwork/node/shared/domain/delegatedStake/UpdateDelegatedStakeValidatorSuite.scala
modules/node-shared/src/test/scala/io/constellationnetwork/node/shared/domain/nodeCollateral/UpdateNodeCollateralValidatorSuite.scala
modules/shared/src/main/scala/io/constellationnetwork/schema/delegatedStake.scala
modules/shared/src/main/scala/io/constellationnetwork/schema/nodeCollateral.scala

+ Adding source field to delegated staking types and updating the tests/validations

feat: adding source to delegated state types

---

modules/dag-l0/src/test/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/GlobalSnapshotConsensusFunctionsSuite.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/node/UpdateNodeParametersValidator.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/modules/SharedValidators.scala
modules/node-shared/src/test/scala/io/constellationnetwork/node/shared/domain/node/UpdateNodeParametersAcceptanceManagerSuite.scala
modules/node-shared/src/test/scala/io/constellationnetwork/node/shared/domain/node/UpdateNodeParametersValidatorSuite.scala

fix: set node parameters for node in seed list only

---

modules/shared/src/main/scala/io/constellationnetwork/currency/schema/currency.scala
modules/shared/src/main/scala/io/constellationnetwork/schema/GlobalSnapshot.scala
modules/shared/src/main/scala/io/constellationnetwork/schema/semver.scala

feat: change schema version to 1.0.0

---

modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/swap/SpendActionValidator.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala
modules/node-shared/src/test/scala/io/constellationnetwork/node/shared/domain/swap/SpendActionValidatorSuite.scala

+ Adding updated on the current allow spends locally during the validation process so that we can reject SpendAction when we have more than one referencing the same AllowSpend in the same snapshot
+ I've split the validation of the SpendActions into the current validate and the new function that will return the accepted and rejected, and call the current validate function
+ This new function is called directly from the GlobalAcceptanceManager, so we can split the responsibilities.
+ It's also easier to create unit tests. I've created unit tests for the scenarios we should accept and reject

fix: updating allow spends during spend action validations

---

modules/dag-l1/src/main/scala/io/constellationnetwork/dag/l1/domain/consensus/block/Validator.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/delegatedStake/UpdateDelegatedStakeValidator.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/GlobalSnapshotAcceptanceManager.scala

+ Adding extra validation to reject delegated stakes to nodeIds without params

fix: reject delegated stakes requests to invalid nodeIds

---

modules/dag-l0/src/main/scala/io/constellationnetwork/dag/l0/infrastructure/snapshot/SnapshotDownloadStorage.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/storage/SnapshotLocalFileSystemStorage.scala

+ Updating the cleanup function to have better logs
+ Adding validations to confirm if all ordinals ahead the rollback one are deleted, if not, stop the starting
In this image, we can see the start being stopped if we have ordinals ahead the rollback:
In this image we can see the start happening normally

feat: adding validation on cleanup function

---

modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/CurrencyL0App.scala
modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/StateChannel.scala
modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/metrics.scala
modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/modules/Services.scala
modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/snapshot/services/StateChannelBinarySender.scala
modules/currency-l0/src/main/scala/io/constellationnetwork/currency/l0/snapshot/services/StateChannelSnapshotService.scala
modules/currency-l0/src/test/scala/io/constellationnetwork/currency/l0/snapshot/services/StateChannelBinarySenderSuite.scala
modules/currency-l1/src/test/scala/io/constellationnetwork/currency/l1/http/DataApplicationRoutesSuite.scala
modules/currency-l1/src/test/scala/io/constellationnetwork/currency/l1/http/TokenLockRoutesSuite.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/domain/cluster/storage/L0ClusterStorage.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/cluster/storage/L0ClusterStorage.scala
modules/node-shared/src/main/scala/io/constellationnetwork/node/shared/infrastructure/snapshot/storage/SnapshotLocalFileSystemStorage.scala

+ Added validations to not allow peers not allowed on the allowance list to send the currency snapshots
+ Implemented unit tests

feat: adding validations to not send currency snapshots if not allowed
